name: Compile ESP32-C6 Sketch

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 Core
        run: |
          arduino-cli core update-index --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://espressif.github.io/arduino-esp32/package_esp32_index.json

      - name: Fix Naming and Compile
        run: |
          # Finds the repo name (C6-Scanner-)
          SKETCH_NAME=$(basename $GITHUB_REPOSITORY)
          # Renames the file ONLY if it's not already named correctly
          if [ ! -f "$SKETCH_NAME.ino" ]; then
            mv *.ino "$SKETCH_NAME.ino"
          fi
          arduino-cli compile --fqbn esp32:esp32:esp32c6 --output-dir ./build ./

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp32c6-firmware
          path: ./build/
